### ISSUE TITLE
Plans to support QUIC?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nnet#43]
Hello,

I understand that nnet supports TCP and KCP (reliable-UDP?), but was wondering if there are any plans to support QUIC as well?

Thanks

**Comment by yilunzhang** [comment]
Not currently as no one tried to run nnet with QUIC yet. Although QUIC is often advertised as a transport layer, IMO it only makes sense to consider QUIC when HTTP is used or needed, at least for now. But anyway, it shouldn't be hard to support QUIC when it's mature enough as a general purposed transport layer, as you can see how simple it is to support kcp: https://github.com/nknorg/nnet/blob/master/transport/kcp.go

**Comment by lonnietc** [comment]
@yilunzhang Thanks so very much for getting back to me on this as I have only briefly played around with QUIC a little and it is still maturing, I think, as you mentioned.  I just also had no experience with kcp but was not sure if it is TCP or
[2023-01-06_06.42.28_LOG.log](https://github.com/nknorg/nnet/files/10359873/2023-01-06_06.42.28_LOG.log)
 UDP based since my understanding is that UDP is significantly faster than TCP and the only latest cutting-edge protocols that seem to be around would be QUIC and FASP (IBM proprietary). I was mostly researching before diving in heavily into NKN which I think now that it will be what I have been seeking for a long time and to use in a project.

I was able to start up a local private testnet with 3 nodes (on the same machine) by using the boot node "nknd -c" and 2 other nodes "nknd" but the 2 nodes only run for a short time and then crash out. (Logs attached).

I think that is has to do with the certs.

**Comment by yilunzhang** [comment]
> UDP is significantly faster than TCP

Not quite. UDP is faster in terms of latency but that's not always what we want. Eventually we need reliable transmission and need to build a TCP-like protocol over UDP (like KCP or QUIC), and it won't be faster than TCP in all scenarios, not to mention TCP is also improving.

> I was able to start up a local private testnet with 3 nodes (on the same machine) by using the boot node "nknd -c" and 2 other nodes "nknd" but the 2 nodes only run for a short time and then crash out. (Logs attached).

Your log shows that those node didn't connect to any neighbors. Are you using the same wallet.json in all those nodes? Each node in the network need a unique wallet.json. If it's still not working, we can continue our discussion in nknorg/nkn repo since it's not relevant to nnet.

**Comment by lonnietc** [comment]
Ah ha, I think that is the part that I missed in the need for each node to have its own unique wallet address and wallet.json

Yea, we can close this since it is now more related to NKN although I am also thinking about trying to use nnet for a P2P graph database effort that I am also interested in setting up and might also be in Golang.
